version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev -- --host" # Ejecuta npm install antes de iniciar Vite
